# -*- coding: utf-8 -*-
"""RAG chatbot ptoject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14maFP1KiUE9cfKbPq3-XVoHx_wT48pma
"""

# Clean uninstall (ignore errors if not installed)
!pip uninstall -y langchain langchain-community langchain-core faiss-cpu sentence-transformers openai

# Install compatible versions (VERY IMPORTANT)
!pip install langchain==0.1.16 \
             langchain-community==0.0.32 \
             langchain-core==0.1.42 \
             faiss-cpu \
             sentence-transformers \
             openai==0.28.1

# Import text splitter to break large text into chunks
from langchain_text_splitters import RecursiveCharacterTextSplitter

# FAISS vector database
from langchain_community.vectorstores import FAISS

# Embedding model (converts text → vectors)
from langchain_community.embeddings import HuggingFaceEmbeddings

# RAG pipeline (Retrieval + LLM)
from langchain.chains import RetrievalQA

# OpenAI LLM
from langchain_community.llms import OpenAI

import os

# Set your OpenAI API key here
# Required for accessing the LLM (GPT model)

os.environ["OPENAI_API_KEY"] = ""

# This is our dataset (documents)
# In real-world, this can be PDFs, websites, or databases

documents = [
    "Machine Learning is a subset of AI that focuses on learning from data.",
    "Deep Learning uses neural networks with many layers.",
    "RAG stands for Retrieval Augmented Generation.",
    "LangChain helps in building LLM-powered applications.",
    "FAISS is used for efficient similarity search and vector storage.",
    "Embeddings convert text into numerical vectors for semantic understanding.",
    "Prompt engineering is important for improving LLM outputs."
]

# Split large text into smaller chunks
# Why? → LLMs and embeddings work better on smaller pieces of text

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=100,     # max size of each chunk
    chunk_overlap=20    # overlap helps maintain context between chunks
)

# Convert raw text into document chunks
docs = text_splitter.create_documents(documents)

# Load embedding model (HuggingFace)
# Converts text → numerical vectors

embeddings = HuggingFaceEmbeddings()

# Store embeddings in FAISS vector database
# FAISS allows fast similarity search

vectorstore = FAISS.from_documents(docs, embeddings)

# Retriever fetches relevant documents based on user query

retriever = vectorstore.as_retriever(
    search_kwargs={"k": 2}  # return top 2 most relevant chunks
)

# Combine retrieval + LLM to form RAG system

qa_chain = RetrievalQA.from_chain_type(
    llm=OpenAI(),        # language model (GPT)
    retriever=retriever, # retrieves relevant context
    chain_type="stuff"   # method to combine retrieved docs
)

# Ask one question at a time (works perfectly in Colab)

query = input("Ask a question: ")

response = qa_chain.run(query)

print("🤖 Answer:", response)